### ISSUE TITLE
jwt 和session的问题

### ISSUE THREAD

**Issue by QiuMing** [howiefh/jee-restful-web#3]
你好，从你的博客和github 中学到不少东西，向你请教关于这个项目的几个问题：
1、 你项目中用的jwt，我理解为它是替代服务器session的，但是你的captcha 中用到session，这样你写出的api 就应该不是完全意义上的restful 了吧，有没考虑过其它的一些方案了，比如把 captcha 放在redis 或者memcached 中？
2、前后端分离，jwt 的有效期是如何处理的，项目中没有看到。。。

**Comment by howiefh** [comment]
1. 刚开始做的时候也没想过完全抛开session，一开始就加入了验证码，后面慢慢 restful 的时候，这块也没有完善。其实还有很多地方需要完善，所以只是一次简单的尝试。
2. 有效期在[LoginCotroller.java](https://github.com/howiefh/jee-restful-web/blob/master/src/main/java/io/github/howiefh/jeews/modules/sys/controller/LoginCotroller.java) 登录的时候jwt配置了
```
// 7 * 24 * 60 * 60 = 604800
options.setExpirySeconds(604800);
```
